version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "takagi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-g4cipmvacz28"
s3_prefix = "takagi"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
