AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  takagi

  Teasing master Takagisan is a simple slack bot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: python3.8
    Environment:
      Variables:
        STAGE: dev
        PYTHONPATH: "${PYTHONPATH}:${PWD}/takagi"


Resources:
  SlackEchoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: s3://takagi/echo
      Handler: takagi/functions.echo.handler
      Events:
        SlackEcho:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /echo
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SlackEchoApi:
    Description: "API Gateway endpoint URL for Prod stage for Slack Echo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/echo/"
  SlackEchoFunction:
    Description: "Slack Echo Lambda Function ARN"
    Value: !GetAtt SlackEchoFunction.Arn
  SlackEchoFunctionIamRole:
    Description: "Implicit IAM Role created for Slack Echo function"
    Value: !GetAtt SlackEchoFunctionRole.Arn
